version: "3"
services:
  kc:
    image: quay.io/keycloak/keycloak:21.0.1
    command: start-dev
    hostname: localhost
    init: true
    network_mode: host
    # required for scripts to monitor java process
    pid: "host"
    environment:
      # matches default of keycloak dev server
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: "8081"
      KC_HTTP_RELATIVE_PATH: /auth/
      KC_HOSTNAME_ADMIN: localhost
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      JAVA_OPTS_APPEND: "-Xms1024m -Xmx2048m"

  scripts:
    build: .
    image: scripts
    init: true
    network_mode: host
    # both required to monitor keycloak with jmap 
    privileged: true
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SEARCH_COUNT: 16
      LDAP_COUNT: 8